-- Supabase <-> OpenClaw durable mailbox and run ledger.
-- Apply as the project owner. RLS is enabled and no anon/authenticated policy is granted.

create extension if not exists pgcrypto;

create table if not exists public.providers (
  id uuid primary key default gen_random_uuid(),
  provider_key text not null unique,
  name text not null,
  available boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_configs (
  id uuid primary key default gen_random_uuid(),
  config_key text not null unique,
  provider_id uuid not null references public.providers(id) on update cascade on delete restrict,
  runtime text not null,
  agent text not null,
  model text,
  effort text,
  available boolean not null default false,
  is_default boolean not null default false,
  other jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  prompt text not null check (length(btrim(prompt)) > 0),
  requested_config text,
  status text not null default 'pending' check (
    status in ('pending', 'claimed', 'running', 'completed', 'failed', 'cancelled', 'timed_out')
  ),
  claimed_by text,
  claimed_at timestamptz,
  lease_expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.runs (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  status text not null default 'created' check (
    status in ('created', 'claimed', 'running', 'completed', 'failed', 'cancelled', 'timed_out')
  ),
  requested_config text,
  used_config text not null,
  fallback_used boolean not null default false,
  fallback_reason text,
  config_id uuid references public.agent_configs(id) on update cascade on delete set null,
  provider_id uuid references public.providers(id) on update cascade on delete set null,
  provider_key text,
  runtime text,
  agent text,
  model text,
  effort text,
  openclaw_task_id text,
  openclaw_run_id text,
  parent_session_key text,
  parent_session_id text,
  error text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on update cascade on delete cascade,
  run_id uuid not null unique references public.runs(id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  status text not null check (status in ('completed', 'failed', 'cancelled', 'timed_out')),
  report_text text not null,
  report jsonb not null default '{}'::jsonb
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  task_id uuid not null references public.tasks(id) on update cascade on delete cascade,
  run_id uuid not null references public.runs(id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  event_ts timestamptz not null,
  source_run_id text,
  source_session_key text,
  source_session_id text,
  source_agent_id text,
  lifecycle_generation text,
  seq bigint,
  stream text,
  event_type text,
  data jsonb not null default '{}'::jsonb
);

create table if not exists public.quota_status (
  id uuid primary key default gen_random_uuid(),
  quota_identity text not null unique,
  provider_id uuid not null references public.providers(id) on update cascade on delete cascade,
  config_id uuid references public.agent_configs(id) on update cascade on delete set null,
  account_key text not null default 'default',
  quota_key text not null,
  remaining numeric,
  limit_value numeric,
  unit text,
  reset_at timestamptz,
  checked_at timestamptz not null,
  status text not null check (status in ('ok', 'unknown', 'unsupported', 'error')),
  source text,
  other jsonb not null default '{}'::jsonb
);

create unique index if not exists agent_configs_one_default_idx
  on public.agent_configs ((is_default)) where is_default;
create index if not exists agent_configs_provider_idx on public.agent_configs(provider_id, available);
create index if not exists tasks_status_created_idx on public.tasks(status, created_at);
create index if not exists tasks_lease_idx on public.tasks(lease_expires_at)
  where status in ('claimed', 'running');
create index if not exists runs_task_created_idx on public.runs(task_id, created_at desc);
create unique index if not exists runs_one_active_per_task_idx on public.runs(task_id)
  where status in ('created', 'claimed', 'running');
create index if not exists runs_openclaw_run_idx on public.runs(openclaw_run_id)
  where openclaw_run_id is not null;
create index if not exists events_run_order_idx on public.events(run_id, event_ts, id);
create index if not exists events_source_run_idx on public.events(source_run_id, seq)
  where source_run_id is not null;
create index if not exists quota_status_provider_idx on public.quota_status(provider_id, account_key, quota_key);

create or replace function public.bridge_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists providers_set_updated_at on public.providers;
create trigger providers_set_updated_at before update on public.providers
for each row execute function public.bridge_set_updated_at();
drop trigger if exists agent_configs_set_updated_at on public.agent_configs;
create trigger agent_configs_set_updated_at before update on public.agent_configs
for each row execute function public.bridge_set_updated_at();
drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks
for each row execute function public.bridge_set_updated_at();

create or replace function public.claim_bridge_task(
  p_task_id uuid,
  p_worker_id text,
  p_lease_seconds integer
)
returns setof public.tasks
language plpgsql
security definer
set search_path = public
as $$
begin
  if length(btrim(p_worker_id)) = 0 then
    raise exception 'worker id is required';
  end if;
  if p_lease_seconds < 60 then
    raise exception 'lease must be at least 60 seconds';
  end if;
  return query
  update public.tasks
  set status = 'claimed',
      claimed_by = p_worker_id,
      claimed_at = now(),
      lease_expires_at = now() + make_interval(secs => p_lease_seconds)
  where id = p_task_id
    and (
      status = 'pending'
      or (status = 'claimed' and coalesce(lease_expires_at, '-infinity'::timestamptz) <= now())
    )
  returning *;
end;
$$;

create or replace function public.renew_bridge_task_lease(
  p_task_id uuid,
  p_worker_id text,
  p_lease_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  update public.tasks
  set lease_expires_at = now() + make_interval(secs => greatest(p_lease_seconds, 60))
  where id = p_task_id
    and claimed_by = p_worker_id
    and status in ('claimed', 'running');
  get diagnostics v_count = row_count;
  return v_count = 1;
end;
$$;

create or replace function public.list_bridge_reconciliation_tasks(p_now timestamptz default now())
returns setof public.tasks
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.tasks
  where status = 'pending'
     or (
       status in ('claimed', 'running')
       and coalesce(lease_expires_at, '-infinity'::timestamptz) <= p_now
     )
  order by created_at, id;
$$;

create or replace function public.refresh_bridge_inventory(
  p_providers jsonb,
  p_configs jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if jsonb_typeof(p_providers) <> 'array' or jsonb_typeof(p_configs) <> 'array' then
    raise exception 'inventory payloads must be JSON arrays';
  end if;

  update public.providers p
  set available = false, updated_at = now()
  where not exists (
    select 1 from jsonb_array_elements(p_providers) item
    where item->>'provider_key' = p.provider_key
  );

  insert into public.providers(provider_key, name, available, metadata, updated_at)
  select
    item->>'provider_key',
    item->>'name',
    coalesce((item->>'available')::boolean, false),
    coalesce(item->'metadata', '{}'::jsonb),
    coalesce((item->>'updated_at')::timestamptz, now())
  from jsonb_array_elements(p_providers) item
  on conflict (provider_key) do update
  set name = excluded.name,
      available = excluded.available,
      metadata = excluded.metadata,
      updated_at = excluded.updated_at;

  -- Clear the old default before setting the newly discovered one so the partial
  -- unique index remains valid even when the default changes.
  update public.agent_configs
  set is_default = false, available = false, updated_at = now()
  where is_default is true or available is true;

  insert into public.agent_configs(
    config_key, provider_id, runtime, agent, model, effort,
    available, is_default, other, updated_at
  )
  select
    item->>'config_key',
    p.id,
    item->>'runtime',
    item->>'agent',
    nullif(item->>'model', ''),
    nullif(item->>'effort', ''),
    coalesce((item->>'available')::boolean, false),
    coalesce((item->>'is_default')::boolean, false),
    coalesce(item->'other', '{}'::jsonb),
    coalesce((item->>'updated_at')::timestamptz, now())
  from jsonb_array_elements(p_configs) item
  join public.providers p on p.provider_key = item->>'provider_key'
  on conflict (config_key) do update
  set provider_id = excluded.provider_id,
      runtime = excluded.runtime,
      agent = excluded.agent,
      model = excluded.model,
      effort = excluded.effort,
      available = excluded.available,
      is_default = excluded.is_default,
      other = excluded.other,
      updated_at = excluded.updated_at;
end;
$$;

create or replace function public.start_bridge_run(
  p_run_id uuid,
  p_task_id uuid,
  p_worker_id text,
  p_requested_config text,
  p_used_config text,
  p_fallback_used boolean,
  p_fallback_reason text,
  p_config_id uuid,
  p_provider_id uuid,
  p_provider_key text,
  p_runtime text,
  p_agent text,
  p_model text,
  p_effort text,
  p_parent_session_key text,
  p_parent_session_id text,
  p_metadata jsonb
)
returns setof public.runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_task_id uuid;
begin
  update public.tasks
  set status = 'running',
      lease_expires_at = greatest(
        coalesce(lease_expires_at, now()),
        now() + interval '60 seconds'
      )
  where id = p_task_id
    and status = 'claimed'
    and claimed_by = p_worker_id
    and coalesce(lease_expires_at, '-infinity'::timestamptz) > now()
  returning id into v_task_id;

  if v_task_id is null then
    return;
  end if;

  insert into public.runs(
    id, task_id, created_at, started_at, status,
    requested_config, used_config, fallback_used, fallback_reason,
    config_id, provider_id, provider_key, runtime, agent, model, effort,
    parent_session_key, parent_session_id, metadata
  ) values (
    p_run_id, p_task_id, now(), now(), 'running',
    p_requested_config, p_used_config, p_fallback_used, p_fallback_reason,
    p_config_id, p_provider_id, p_provider_key, p_runtime, p_agent, p_model, p_effort,
    p_parent_session_key, p_parent_session_id, coalesce(p_metadata, '{}'::jsonb)
  );

  return query select * from public.runs where id = p_run_id;
end;
$$;

create or replace function public.fail_claimed_bridge_task(
  p_task_id uuid,
  p_worker_id text,
  p_error text,
  p_report_text text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_task_id uuid;
  v_run_id uuid := gen_random_uuid();
begin
  update public.tasks
  set status = 'failed',
      lease_expires_at = null,
      metadata = metadata || jsonb_build_object(
        'bridge_start_error', p_error,
        'bridge_start_report', p_report_text
      )
  where id = p_task_id
    and status in ('claimed', 'running')
    and (
      claimed_by = p_worker_id
      or coalesce(lease_expires_at, '-infinity'::timestamptz) <= now()
    )
  returning id into v_task_id;

  if v_task_id is null then
    return false;
  end if;

  insert into public.runs(
    id, task_id, created_at, started_at, finished_at, status,
    used_config, fallback_used, error, metadata
  ) values (
    v_run_id, p_task_id, now(), now(), now(), 'failed',
    'unavailable', false, p_error, jsonb_build_object('failed_before_execution', true)
  );
  insert into public.reports(task_id, run_id, status, report_text, report)
  values (
    p_task_id, v_run_id, 'failed', p_report_text,
    jsonb_build_object('summary', p_report_text, 'error', p_error)
  );
  return true;
end;
$$;

create or replace function public.complete_bridge_run(
  p_run_id uuid,
  p_report_text text,
  p_report jsonb,
  p_metadata jsonb,
  p_openclaw_run_id text,
  p_openclaw_task_id text,
  p_actual_provider_key text,
  p_actual_model text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_task_id uuid;
begin
  update public.runs
  set status = 'completed',
      finished_at = now(),
      openclaw_run_id = coalesce(p_openclaw_run_id, openclaw_run_id),
      openclaw_task_id = coalesce(p_openclaw_task_id, openclaw_task_id),
      provider_key = coalesce(p_actual_provider_key, provider_key),
      model = coalesce(p_actual_model, model),
      metadata = metadata || coalesce(p_metadata, '{}'::jsonb)
  where id = p_run_id
    and status not in ('completed', 'failed', 'cancelled', 'timed_out')
  returning task_id into v_task_id;

  if v_task_id is null then
    return false;
  end if;

  update public.tasks
  set status = 'completed', lease_expires_at = null
  where id = v_task_id and status not in ('completed', 'failed', 'cancelled', 'timed_out');

  insert into public.reports(task_id, run_id, status, report_text, report)
  values (v_task_id, p_run_id, 'completed', p_report_text, coalesce(p_report, '{}'::jsonb))
  on conflict (run_id) do nothing;
  return true;
end;
$$;

create or replace function public.fail_bridge_run(
  p_run_id uuid,
  p_status text,
  p_error text,
  p_report_text text,
  p_report jsonb,
  p_metadata jsonb,
  p_openclaw_run_id text,
  p_openclaw_task_id text,
  p_actual_provider_key text,
  p_actual_model text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_task_id uuid;
begin
  if p_status not in ('failed', 'cancelled', 'timed_out') then
    raise exception 'invalid terminal status: %', p_status;
  end if;

  update public.runs
  set status = p_status,
      finished_at = now(),
      error = p_error,
      openclaw_run_id = coalesce(p_openclaw_run_id, openclaw_run_id),
      openclaw_task_id = coalesce(p_openclaw_task_id, openclaw_task_id),
      provider_key = coalesce(p_actual_provider_key, provider_key),
      model = coalesce(p_actual_model, model),
      metadata = metadata || coalesce(p_metadata, '{}'::jsonb)
  where id = p_run_id
    and status not in ('completed', 'failed', 'cancelled', 'timed_out')
  returning task_id into v_task_id;

  if v_task_id is null then
    return false;
  end if;

  update public.tasks
  set status = p_status, lease_expires_at = null
  where id = v_task_id and status not in ('completed', 'failed', 'cancelled', 'timed_out');

  insert into public.reports(task_id, run_id, status, report_text, report)
  values (v_task_id, p_run_id, p_status, p_report_text, coalesce(p_report, '{}'::jsonb))
  on conflict (run_id) do nothing;
  return true;
end;
$$;

alter table public.providers enable row level security;
alter table public.agent_configs enable row level security;
alter table public.tasks enable row level security;
alter table public.runs enable row level security;
alter table public.reports enable row level security;
alter table public.events enable row level security;
alter table public.quota_status enable row level security;

-- The bridge credential is expected to use service_role initially, or a later
-- dedicated role with narrowly granted table/function rights. No anon or broad
-- authenticated policy is created here.
revoke all on public.providers, public.agent_configs, public.tasks, public.runs,
  public.reports, public.events, public.quota_status from anon, authenticated;
grant all on public.providers, public.agent_configs, public.tasks, public.runs,
  public.reports, public.events, public.quota_status to service_role;
grant usage, select on sequence public.events_id_seq to service_role;

revoke all on function public.claim_bridge_task(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.renew_bridge_task_lease(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.list_bridge_reconciliation_tasks(timestamptz) from public, anon, authenticated;
revoke all on function public.refresh_bridge_inventory(jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.start_bridge_run(uuid, uuid, text, text, text, boolean, text, uuid, uuid, text, text, text, text, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.fail_claimed_bridge_task(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.complete_bridge_run(uuid, text, jsonb, jsonb, text, text, text, text) from public, anon, authenticated;
revoke all on function public.fail_bridge_run(uuid, text, text, text, jsonb, jsonb, text, text, text, text) from public, anon, authenticated;

grant execute on function public.claim_bridge_task(uuid, text, integer) to service_role;
grant execute on function public.renew_bridge_task_lease(uuid, text, integer) to service_role;
grant execute on function public.list_bridge_reconciliation_tasks(timestamptz) to service_role;
grant execute on function public.refresh_bridge_inventory(jsonb, jsonb) to service_role;
grant execute on function public.start_bridge_run(uuid, uuid, text, text, text, boolean, text, uuid, uuid, text, text, text, text, text, text, text, jsonb) to service_role;
grant execute on function public.fail_claimed_bridge_task(uuid, text, text, text) to service_role;
grant execute on function public.complete_bridge_run(uuid, text, jsonb, jsonb, text, text, text, text) to service_role;
grant execute on function public.fail_bridge_run(uuid, text, text, text, jsonb, jsonb, text, text, text, text) to service_role;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'tasks'
     ) then
    alter publication supabase_realtime add table public.tasks;
  end if;
end;
$$;

comment on table public.tasks is 'Durable low-volume mailbox from ChatGPT to OpenClaw.';
comment on table public.events is 'Sanitized operational event log; local OpenClaw transcripts remain the forensic source.';
comment on column public.runs.provider_key is 'Historical provider identity even if the provider inventory later changes.';
comment on column public.quota_status.remaining is 'Provider-reported or provider-derived remaining amount only; never guessed.';
